In [1]:
import torch
torch.cuda.is_available() #代表显卡是否可用
torch.cuda.device_count() #检测显卡的数量
torch.cuda.get_device_name(0) #最后查看一下咱们显卡的名字
x = torch.rand(5,6)
print(x)

tensor([[0.5267, 0.0657, 0.3071, 0.7497, 0.3072, 0.4728],
        [0.8234, 0.2056, 0.8541, 0.3286, 0.3222, 0.5401],
        [0.2645, 0.6236, 0.9254, 0.7672, 0.3723, 0.2386],
        [0.5234, 0.6438, 0.4987, 0.4857, 0.8132, 0.2906],
        [0.5919, 0.2128, 0.0605, 0.5449, 0.8950, 0.1822]])


首先导入Pytorch的库，然后我们用下面代码来测试咱们的显卡是否可用

如果显示 `False`，可以先去检查显卡型号是否支持Pytorch

如果支持，就去更新一下显卡驱动，说不定是因为驱动太老的缘故

In [2]:
torch.cuda.is_available() #代表显卡是否可用

True

In [3]:
torch.cuda.device_count() #检测显卡的数量

1

In [4]:
torch.cuda.get_device_name(0) #最后查看一下咱们显卡的名字

'NVIDIA GeForce GTX 960M'

在确认我们的显卡可以使用后，我们来看一下Pytorch的一些基础语法

---

torch.rand()随机化一个 5 $\times$ 6 的矩阵

In [5]:
x = torch.rand(5,6)
print(x)

tensor([[0.6852, 0.2343, 0.5173, 0.1813, 0.7338, 0.1112],
        [0.0158, 0.9812, 0.0948, 0.5431, 0.7804, 0.5421],
        [0.6776, 0.7374, 0.8789, 0.3494, 0.1321, 0.7051],
        [0.2467, 0.5686, 0.5608, 0.7104, 0.4090, 0.3330],
        [0.0661, 0.6282, 0.3280, 0.1022, 0.1161, 0.7491]])


torch.ones()初始化一个 5 $\times$ 6 的矩阵，值全部为1

In [6]:
x = torch.ones(5,6)
print(x)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


torch.zeros()初始化一个 4 $\times$ 4 的矩阵，值全部为0

In [7]:
x = torch.zeros(4,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
