In [1]:
import torch
torch.cuda.is_available() #代表显卡是否可用
torch.cuda.device_count() #检测显卡的数量
torch.cuda.get_device_name(0) #最后查看一下咱们显卡的名字
x = torch.rand(5,6)
print(x)

tensor([[0.6054, 0.9425, 0.2271, 0.9820, 0.5712, 0.1021],
        [0.1594, 0.1650, 0.7790, 0.4353, 0.9686, 0.8008],
        [0.4166, 0.7109, 0.2115, 0.3037, 0.8605, 0.5731],
        [0.6830, 0.4746, 0.6436, 0.9940, 0.7133, 0.4708],
        [0.6369, 0.6278, 0.3372, 0.4690, 0.1788, 0.9052]])


首先导入Pytorch的库，然后我们用下面代码来测试咱们的显卡是否可用

如果显示 `False`，可以先去检查显卡型号是否支持Pytorch

如果支持，就去更新一下显卡驱动，说不定是因为驱动太老的缘故

In [2]:
torch.cuda.is_available() #代表显卡是否可用

True

In [3]:
torch.cuda.device_count() #检测显卡的数量

1

In [4]:
torch.cuda.get_device_name(0) #最后查看一下咱们显卡的名字

'NVIDIA GeForce GTX 960M'

在确认我们的显卡可以使用后，我们来看一下Pytorch的一些基础语法

---

torch.rand()随机化一个 5 $\times$ 6 的矩阵

In [5]:
x = torch.rand(5,6)
print(x)

tensor([[0.6552, 0.9870, 0.4958, 0.3635, 0.4721, 0.1429],
        [0.9073, 0.2979, 0.4702, 0.9344, 0.3838, 0.6681],
        [0.5420, 0.9571, 0.1718, 0.7732, 0.5532, 0.6224],
        [0.6138, 0.3082, 0.2103, 0.8417, 0.7497, 0.7415],
        [0.1941, 0.3484, 0.6971, 0.0189, 0.8726, 0.1769]])


torch.ones()初始化一个 5 $\times$ 6 的矩阵，值全部为1

In [6]:
x = torch.ones(5,6)
print(x)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


torch.zeros()初始化一个 4 $\times$ 4 的矩阵，值全部为0

In [7]:
x = torch.zeros(4,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
